### ISSUE TITLE
How are you handling CVE?

### ISSUE THREAD

**Issue by rjmcguire** [etcimon/libhttp2#3]
How are you handling CVE?
How directly do CVEs on nghttp2 apply to libhttp2?

Cheers,
R

**Comment by etcimon** [comment]
The code is practically the same so the CVE from nghttp2 applies to libhttp2, however nghttp2 includes a webserver which will contain most of the vulnerabilities and this won't affect libhttp2. If you find a vulnerability just send me an email about it and I will resolve it

**Comment by rjmcguire** [comment]
The thought that made me ask is:

Suppose there is a vulnerability announced  in nghttp2, someone could then
target forks or ports of nghttp2 in the hopes of finding easy targets.

I wondered if you had used slices etc instead of pointers etc...

**Comment by etcimon** [comment]
I used slices in critical areas and pointers in other places. I think it will require some security analysis to know for sure

**Comment by rjmcguire** [comment]
I'll close this issue. I think the only real option is to follow nghttp2
and then make unittests for any CVEs they encounter.

No time for even that though, but perhaps some time will become available
in future.

Thanks!

**Comment by etcimon** [comment]
I see only 1 vulnerability on nghttp2 in the CVE which coincides with this patch: https://github.com/nghttp2/nghttp2/commit/b7159f80b20432d510d43d9c8b57cf3f2b39159b

I'll take some time this week to merge it, but it looks like everything looks safe other than that. The protocol itself should have been designed with security in mind.

**Comment by etcimon** [comment]
Actually it looks like this vulnerability was introduced in this commit which I didn't mirror:
https://github.com/nghttp2/nghttp2/commit/5b59e46e2bb4a5b07cf040e6e10a4f7457fa06cd
